/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libreriad;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import static libreriad.MuestraImage.cadenaDig;

/**
 *
 * @author USUARIO
 */
public class STiempo extends javax.swing.JFrame {
    
    AlgoritmoBerkeley ab; //Todo lo relacionado con el algoritmo
    String tiempo;
    int segundero=1000;

    /**
     * Creates new form STiempo
     */
    public STiempo() {
        initComponents();
        iniciarRelojes();
        ab = new AlgoritmoBerkeley();
        //Asignar tiempo a el servidor
        Date date = new Date();
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        ab.tiempo = hourFormat.format(date);
        System.out.println("El tiempo es: "+ab.tiempo);
        ab.hiloEscuchaEquipos();
        ab.berkeley();
    }
    
    public void iniciarRelojes(){
        Date date = new Date();
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        lbtime.setText(hourFormat.format(date));
        Thread hilo = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    int seg=0, min, hor;
                    while(true){
                        tiempo = lbtime.getText();

                        seg = Integer.parseInt(tiempo.substring(tiempo.lastIndexOf(":")+1));
                        min = Integer.parseInt(tiempo.substring(tiempo.indexOf(":")+1,tiempo.lastIndexOf(":")));
                        hor = Integer.parseInt(tiempo.substring(0,2));
                        if(seg <59) seg++;
                        else{
                            seg=0;
                            if(min<59) min++;
                            else{
                                min=0;
                                if(hor<23) hor++;
                                else hor=0;
                            }
                        }

                            lbtime.setText(cadenaDig(hor)+":"+cadenaDig(min)+":"+cadenaDig(seg));
                            Thread.sleep(segundero);
                    System.out.print("");
                    }
                } catch (Exception ex) {
                    System.out.println("Error en hilo "+ex);
                }
            }
        });

        //Iniciar los hilos
        hilo.start();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbtime.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(lbtime)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lbtime)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STiempo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbtime;
    // End of variables declaration//GEN-END:variables
}
